[package]
name = "terminal-kernel-alacritty"
version.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
alacritty_terminal.workspace = true
config = { path = "../config" }
futures.workspace = true
terminal = { path = "../terminal" }
terminal-kernel = { path = "../terminal-kernel" }

[lints]
workspace = true
