name: PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-11-arm, ubuntu-24.04-arm, macos-latest, macos-26-intel]
    steps:
      - uses: actions/checkout@sha256:0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Cache
        uses: actions/cache@sha256:668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && sudo apt install -y \
            clang \
            llvm \
            libxcb1-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev

      - name: Build
        run: cargo build

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --locked

      - name: Run coverage (tests included)
        if: ${{ !(runner.os == 'Windows' && runner.arch == 'ARM64') }}
        run: |
          mkdir -p ./coverage
          cargo llvm-cov --workspace --all-features --lcov --output-path coverage/lcov.info

      - name: Upload coverage artifact
        uses: actions/upload-artifact@sha256:043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: runner.os == 'Linux' && runner.arch == 'X64'
        with:
          name: coverage-lcov
          path: coverage/lcov.info
